### ISSUE TITLE
Vertical line in place of Union does not pass the types check

### ISSUE THREAD

**Issue by AndreyKarnauhov** [fipl-hse/2022-2-level-labs#79]
Seemingly the case is mypy does not support Python 3.10 features.

Example of a commit with this issue:
https://github.com/fipl-hse/2022-2-level-labs/pull/33/commits/0da5b89f7b9c37ac09f811119bc8471aa88c89dd

main.py line 186:
```
if not (is_dic_correct(frequencies, False, str, int | float) and my_isinstance(top, int) and top > 0):
```

Check types output:
```
lab_1_keywords_tfidf/main.py:186: error: Argument 3 to "is_dic_correct" has incompatible type "Type[str]"; expected "Union[int, float, str, Tuple[Any, ...]]"  [arg-type]
lab_1_keywords_tfidf/main.py:186: error: Unsupported left operand type for | ("Type[int]")  [operator]
```

**Comment by artyomtugaryov** [comment]
Can you share a link to this CI run?

**Comment by artyomtugaryov** [comment]
I found the run - https://github.com/fipl-hse/2022-2-level-labs/actions/runs/3154096229/jobs/5131318546

**Comment by AndreyKarnauhov** [comment]
Merging dictionaries with `|` provokes an error as well.

Commit: https://github.com/fipl-hse/2022-2-level-labs/pull/80/commits/e15df15fb116c4bc2d5694ea6ca25ed027dd94e3

CI run: https://github.com/fipl-hse/2022-2-level-labs/actions/runs/3185903115/jobs/5195982864

Line 101 in start.py:
```
FINAL_CUMULATIVE_SCORE = KEYWORD_PHRASES_WITH_SCORES | CUMULATIVE_SCORE_WITH_STOP_WORDS
```

Check types output:
```
lab_2_keywords_cooccurrence/start.py:101: error: Unsupported left operand type for | ("Mapping[Tuple[str, ...], float]")  [operator]
lab_2_keywords_cooccurrence/start.py:101: error: Unsupported left operand type for | ("None")  [operator]
lab_2_keywords_cooccurrence/start.py:101: note: Both left and right operands are unions
```

**Comment by artyomtugaryov** [comment]
I investigated the bug and found that the problem is in mypy - https://github.com/python/mypy/issues/12392
And we just have to wait for a decision from the mypy project. The workaround I can suggest is just use `Union` instead of `|`
